import { SERVICE_NAMES } from './service-names';

export const SERVICE_PORTS: Record<SERVICE_NAMES, number> = {
  [SERVICE_NAMES.USER]: 3012,
  [SERVICE_NAMES.PRODUCT]: 3001,
  [SERVICE_NAMES.ORDER]: 3002,
  [SERVICE_NAMES.RATING]: 3003,
  [SERVICE_NAMES.EMAIL]: 3004,
  [SERVICE_NAMES.PAYMENT]: 3005,
  [SERVICE_NAMES.SEARCH]: 3006,
  [SERVICE_NAMES.CART]: 3020,
  [SERVICE_NAMES.ADMIN]: 3008,
  [SERVICE_NAMES.INVOICE]: 3009,
  [SERVICE_NAMES.ANALYTICS]: 3010,
  [SERVICE_NAMES.VENDOR]: 3011,
};
